export const GET_ALLPRODUCT_REQUEST = "GET_ALLPRODUCT_REQUEST";
export const GET_ALLPRODUCT_SUCCESS = "GET_ALLPRODUCT_SUCCESS";
export const GET_ALLPRODUCT_FAILED = "GET_ALLPRODUCT_FAILED";

export const GET_SINGELPRODUCT = "GET_SINGELPRODUCT";

export const SHOW_ALLITEMS_IN_CART = "SHOW_ALLITEMS_IN_CART";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
